### ISSUE TITLE
Unable to launch minitiad (minimove)

### ISSUE THREAD

**Issue by serkanalgl** [initia-labs/minimove#46]
Unable to launch minitiad (minimove).

**Expected behavior**

Once the launch steps successfully completes, two artifact files will be generated in the directory $HOME/.minitia/artifacts

**Actual behavior**

I got an error "panic: runtime error: invalid memory address or nil pointer dereference"

**To reproduce**

`
minitiad launch initiation-1 --with-config config.json

7:09PM INF initializing RPC helpers l1-chain-id=initiation-1 l1-rpc-url=https://initia-testnet-rpc.polkachu.com:443
7:09PM INF initializing RPC helpers l2-chain-id=minitia-1 l2-rpc-url=http://localhost:26657
7:09PM INF initializing genesis
7:09PM INF created node identity chain_id=minitia-1 moniker=operator node_id=a67b7db0599f42cdfff82ffff1820ce063a65c0b validator_address=init1gfhfujxen8jqgllud3f08fdt88n36t49vzv28a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x105a4c268]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/genutil/types.(*AppGenesis).ValidateAndComplete(0x1400198a2b8?)
	github.com/cosmos/cosmos-sdk@v0.50.6/x/genutil/types/genesis.go:54 +0x18
github.com/cosmos/cosmos-sdk/x/genutil.ExportGenesisFile(0x0, {0x1400154cf60, 0x2f})
	github.com/cosmos/cosmos-sdk@v0.50.6/x/genutil/utils.go:25 +0x28
github.com/initia-labs/OPinit/contrib/launchtools/steps.InitializeGenesis.InitializeGenesis.InitializeGenesisWithPostSetup.func1.func2({0x1089013f8, 0x140031f0090})
	github.com/initia-labs/OPinit@v0.2.9/contrib/launchtools/steps/genesis.go:70 +0x164
github.com/initia-labs/OPinit/contrib/launchtools.LaunchCmd.func1(0x140012b3b08, {0x1400279f530, 0x1, 0x3?})
	github.com/initia-labs/OPinit@v0.2.9/contrib/launchtools/cmd.go:84 +0x49c
github.com/spf13/cobra.(*Command).execute(0x140012b3b08, {0x1400279f4a0, 0x3, 0x3})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x14002f64c08)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.8.0/command.go:1032
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x14002f64c08, {0x10726a617, 0x7}, {0x14000ee7220, 0x1b})
	github.com/cosmos/cosmos-sdk@v0.50.6/server/cmd/execute.go:34 +0x154
main.main()
	github.com/initia-labs/minimove/cmd/minitiad/main.go:15 +0x40`

here is the config.json:
`
{
  "l1_config": {
    "chain_id": "initiation-1",
    "rpc_url": "https://rpc-initia.01node.com:443",
    "gas_prices": "0.15move/944f8dd8dc49f96c25fea9849f16436dcfa6d564eec802f3ef7f8b3ea85368ff"
  },
  "l2_config": {
    "chain_id": "minitia-1",
    "denom": "umin",
    "moniker": "operator"
  },
  "op_bridge": {
    "output_submission_start_time": "2024-06-28T11:15:15.113678+03:00",
    "output_submission_interval": 3600000000000,
    "output_finalization_period": 3600000000000,
    "batch_submission_target": "l1"
  },
  "system_keys": {
    "validator": {
      "address": "init1gfhfujxen8jqgllud3f08fdt88n36t49vzv28a",
      "mnemonic": "bla bla bla"
    },
    "bridge_executor": {
      "address": "init1tga248dnp4gl5lrw5hyxu8z6v3jkga24awgkhg",
      "mnemonic": "bla bla bla"
    },
    "output_submitter": {
      "address": "init15a3nzt7xjx3ghzj3hc0f66c6cxrfsatfsw7qjl",
      "mnemonic": "bla bla bla"
    },
    "batch_submitter": {
      "address": "init154xvgcpdcaf5uat9tkwz26szsjlwr9ct36ukfs",
      "mnemonic": "bla bla bla"
    },
    "challenger": {
      "address": "init193r4nky4thmza3s94udzsc93glrt3450wnt4hp",
      "mnemonic": "bla bla bla"
    }
  },
  "genesis_accounts": [
    {
      "address": "init1gfhfujxen8jqgllud3f08fdt88n36t49vzv28a"
    },
    {
      "address": "init1tga248dnp4gl5lrw5hyxu8z6v3jkga24awgkhg"
    },
    {
      "address": "init15a3nzt7xjx3ghzj3hc0f66c6cxrfsatfsw7qjl"
    },
    {
      "address": "init154xvgcpdcaf5uat9tkwz26szsjlwr9ct36ukfs"
    },
    {
      "address": "init193r4nky4thmza3s94udzsc93glrt3450wnt4hp"
    }
  ]
}
`

**System information**

minitiad version v0.2.16
go version go1.22.4 darwin/arm64

**Comment by JSHan94** [comment]
@serkanalgl  sry for late reply. you have to remove your `${HOME}/.minitia` directory before you use `launch` cmd.
it will remake the node, so the original minitia node will interrupt it.

**Comment by serkanalgl** [comment]
Hi @JSHan94, actually I removed ".minitia" directory before launch command and it gave that error. Nevermind, I can not reproduce this error right now. Thank you.
